service:
  name: q-and-a-backend

custom:
  dynamodb-offline-port: 8000
  dynamodb:
    stages:
      - dev
    start:
      port: ${self:custom.dynamodb-offline-port}
      dbPath: db/
      migrate: true
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm'
  serverless-offline:
    useChildProcesses: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

resources:
  - ${file(./resources/dynamodb-meetings-table.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  logs:
    restApi: true

functions:
  getMeeting:
    handler: src/meeting/controller.getMeeting
    events:
      - http:
          method: get
          path: meetings/{id}
          cors: true
  createMeeting:
    handler: src/meeting/controller.createMeeting
    events:
      - http:
          method: post
          path: meetings/
          cors: true
  