service:
  name: q-and-a-backend

custom:
  dynamodb-offline-port: 8000
  dynamodb:
    stages:
      - development
    start:
      port: ${self:custom.dynamodb-offline-port}
      dbPath: db/
      migrate: true
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: npm
  serverless-offline:
    httpPort: 8080
    useChildProcesses: true
  middleware:
    pre:
      - src/common/middleware/global-imports.noop
    pos:
      - catch: src/common/middleware/error-handler.errorHandler

plugins:
  - serverless-dotenv-plugin
  - serverless-middleware
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

resources:
  - ${file(./resources/api-gateway-cognito-authorizer.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'us-west-2'}
  profile: ${opt:profile, 'q-and-a-admin'}
  apiGateway:
    minimumCompressionSize: 1024

functions:
  # Meeting endpoints
  getMeeting:
    handler: src/meeting/handler.getMeeting
    events:
      - http:
          method: get
          path: meetings/{meetingId}
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: APIGatewayCognitoAuthorizer
  createMeeting:
    handler: src/meeting/handler.createMeeting
    events:
      - http:
          method: post
          path: meetings
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: APIGatewayCognitoAuthorizer
  deleteMeeting:
    handler: src/meeting/handler.deleteMeeting
    events:
      - http:
          method: delete
          path: meetings/{meetingId}
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: APIGatewayCognitoAuthorizer
  updateMeeting:
    handler: src/meeting/handler.updateMeeting
    events:
      - http:
          method: patch
          path: meetings/{meetingId}
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: APIGatewayCognitoAuthorizer
  getQuestionsOfMeeting:
    handler: src/meeting/handler.getQuestionsOfMeeting
    events:
      - http:
          method: get
          path: meetings/{meetingId}/questions
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: APIGatewayCognitoAuthorizer
  # Question endpoints
  createQuestion:
    handler: src/question/handler.createQuestion
    events:
      - http:
          method: post
          path: questions
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: APIGatewayCognitoAuthorizer
  updateVoteCountsOfQuestions:
    handler: src/question/handler.updateVoteCountsOfQuestions
    events:
      - stream:
          enabled: true
          type: dynamodb
          arn:
            Fn::ImportValue: VotesTableStreamArn-${self:provider.stage}
          batchSize: 10
          startingPosition: LATEST
  # Vote endpoints
  voteQuestion:
    handler: src/vote/handler.voteQuestion
    events:
      - http:
          method: put
          path: questions/{questionId}/vote
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: APIGatewayCognitoAuthorizer
  getVotesOfCurrentUser:
    handler: src/vote/handler.getVotesOfCurrentUser
    events:
      - http:
          method: get
          path: meetings/{meetingId}/users/me/votes
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: APIGatewayCognitoAuthorizer
