Resources:
  APIGatewayCognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId:
        Ref: ApiGatewayRestApi
      ProviderARNs:
        - Fn::ImportValue: CognitoUserPoolArn-${self:provider.stage}
Outputs:
  CognitoAuthorizer:
    Value:
      Ref: APIGatewayCognitoAuthorizer
