Resources:
  CognitoUserPoolGoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      AttributeMapping:
        email: email
        name: name
        picture: picture
      ProviderDetails:
        client_id: ${env:GOOGLE_CLIENT_ID}
        client_secret: ${env:GOOGLE_CLIENT_SECRET}
        authorize_scopes: profile email openid
      ProviderName: Google
      ProviderType: Google
      UserPoolId: !Ref CognitoUserPool
Outputs:
  UserPoolGoogleIdentityProvider:
    Value:
      Ref: CognitoUserPoolGoogleIdentityProvider
