Resources:
  QuestionsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      TableName: ${env:QUESTIONS_TABLE}-${self:provider.stage}
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: meetingId
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        -
          IndexName: meetingId-id-index
          KeySchema:
            -
              AttributeName: meetingId
              KeyType: HASH
            -
              AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${env:QUESTIONS_TABLE_READ_THROUGHPUT}
            WriteCapacityUnits: ${env:QUESTIONS_TABLE_WRITE_THROUGHPUT}
      ProvisionedThroughput:
        ReadCapacityUnits: ${env:QUESTIONS_TABLE_READ_THROUGHPUT}
        WriteCapacityUnits: ${env:QUESTIONS_TABLE_WRITE_THROUGHPUT}
Outputs:
  QuestionsTableArn:
    Value:
      "Fn::GetAtt": [ QuestionsTable, Arn ]
