Resources:
  MeetingsTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      TableName: ${env:MEETINGS_TABLE}-${self:provider.stage}
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: userId
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        -
          IndexName: userId-id-index
          KeySchema:
            -
              AttributeName: userId
              KeyType: HASH
            -
              AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${env:MEETINGS_TABLE_READ_THROUGHPUT}
            WriteCapacityUnits: ${env:MEETINGS_TABLE_WRITE_THROUGHPUT}
      ProvisionedThroughput:
        ReadCapacityUnits: ${env:MEETINGS_TABLE_READ_THROUGHPUT}
        WriteCapacityUnits: ${env:MEETINGS_TABLE_WRITE_THROUGHPUT}
Outputs:
  MeetingsTableArn:
    Value:
      "Fn::GetAtt": [ MeetingsTable, Arn ]
